Q1. Pandas version

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.1'

In [3]:
# cargar el dataset desde un URL
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
# cargar el dataset desde un archivo local
#df = pd.read_csv("./car_fuel_efficiency.csv")
df.head(3)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341

Q2. Records count

In [4]:
len(df)

9704

In [5]:
df.isnull()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9699,False,False,False,False,False,False,False,False,False,True,False
9700,False,True,False,False,False,False,False,False,False,False,False
9701,False,False,False,False,False,False,False,False,False,False,False
9702,False,False,False,False,False,False,False,False,False,False,False
9703,False,False,False,False,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

Q3. Fuel types

In [8]:
df.fuel_type.nunique()

2

In [9]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [10]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

Q4. Missing values

In [11]:
df.isnull().any().sum()

np.int64(4)

Q5. Max fuel efficiency

In [12]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [13]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

Q6. Median value of horsepower

Find the median value of horsepower column in the dataset.

In [14]:
df.horsepower.median()

np.float64(149.0)

Next, calculate the most frequent value of the same horsepower column.

In [15]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

In [16]:
df.head(20)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
5,190,3.0,NaN,2484.883986,14.7,2008,Europe,Gasoline,All-wheel drive,-1.0,17.271818
6,240,7.0,127.0,3006.542287,22.2,2012,USA,Gasoline,Front-wheel drive,1.0,13.210412
7,150,4.0,239.0,3638.657780,17.3,2020,USA,Diesel,All-wheel drive,1.0,12.848884
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
9,150,4.0,123.0,3509.036569,10.2,2005,USA,Gasoline,Front-wheel drive,-1.0,12.298355
10,230,5.0,100.0,3111.810181,15.4,2014,Europe,Diesel,All-wheel drive,0.0,13.386605
11,150,5.0,NaN,1967.200421,12.6,2014,USA,Diesel,Front-wheel drive,2.0,20.504447
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
13,170,1.0,193.0,2274.735191,17.5,2000,Europe,Diesel,Front-wheel drive,0.0,18.792742
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
15,220,4.0,179.0,2631.065204,16.0,2006,USA,Gasoline,All-wheel drive,1.0,16.756081
16,160,3.0,180.0,2673.552941,8.5,2013,Europe,Diesel,All-wheel drive,-1.0,17.516176
17,190,6.0,132.0,2427.311856,17.8,2011,USA,Diesel,Front-wheel drive,-1.0,17.658685
18,250,2.0,110.0,2971.214575,NaN,2003,Europe,Gasoline,Front-wheel drive,1.0,14.735962
19,180,1.0,126.0,2986.958657,17.9,2004,Europe,Gasoline,All-wheel drive,-1.0,15.097137

In [17]:
df.horsepower.fillna(df.horsepower.mode()[0], inplace=True)
df.head(30)

/tmp/ipykernel_7609/1690258524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.horsepower.fillna(df.horsepower.mode()[0], inplace=True)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,152.0,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
5,190,3.0,152.0,2484.883986,14.7,2008,Europe,Gasoline,All-wheel drive,-1.0,17.271818
6,240,7.0,127.0,3006.542287,22.2,2012,USA,Gasoline,Front-wheel drive,1.0,13.210412
7,150,4.0,239.0,3638.657780,17.3,2020,USA,Diesel,All-wheel drive,1.0,12.848884
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
9,150,4.0,123.0,3509.036569,10.2,2005,USA,Gasoline,Front-wheel drive,-1.0,12.298355
10,230,5.0,100.0,3111.810181,15.4,2014,Europe,Diesel,All-wheel drive,0.0,13.386605
11,150,5.0,152.0,1967.200421,12.6,2014,USA,Diesel,Front-wheel drive,2.0,20.504447
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
13,170,1.0,193.0,2274.735191,17.5,2000,Europe,Diesel,Front-wheel drive,0.0,18.792742
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
15,220,4.0,179.0,2631.065204,16.0,2006,USA,Gasoline,All-wheel drive,1.0,16.756081
16,160,3.0,180.0,2673.552941,8.5,2013,Europe,Diesel,All-wheel drive,-1.0,17.516176
17,190,6.0,132.0,2427.311856,17.8,2011,USA,Diesel,Front-wheel drive,-1.0,17.658685
18,250,2.0,110.0,2971.214575,NaN,2003,Europe,Gasoline,Front-wheel drive,1.0,14.735962
19,180,1.0,126.0,2986.958657,17.9,2004,Europe,Gasoline,All-wheel drive,-1.0,15.097137
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
22,190,1.0,144.0,2438.842126,16.4,2016,Europe,Diesel,Front-wheel drive,1.0,17.080405
23,230,2.0,160.0,3342.606027,12.9,2009,Europe,Gasoline,All-wheel drive,0.0,13.738381
24,260,3.0,156.0,4267.390497,20.0,2004,USA,Diesel,Front-wheel drive,1.0,7.853194
25,210,6.0,157.0,2860.206191,12.6,2013,USA,Gasoline,All-wheel drive,NaN,15.906422
26,180,8.0,160.0,3080.170162,10.6,2002,USA,Diesel,All-wheel drive,2.0,15.089880
27,120,6.0,206.0,3467.355490,18.3,2016,USA,Gasoline,Front-wheel drive,-1.0,13.048993
28,220,4.0,154.0,3335.068187,14.8,2005,USA,Diesel,All-wheel drive,-1.0,13.411266
29,230,4.0,132.0,2479.782974,15.6,2014,Europe,Diesel,All-wheel drive,0.0,17.349011

Now, calculate the median value of horsepower once again.

In [18]:
df.horsepower.median()

np.float64(152.0)

Has it changed?

Yes, it increased

Q7. Sum of weights

Select all the cars from Asia

In [19]:
df[
    df['origin'] == 'Asia'
]

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,152.0,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

Select only columns vehicle_weight and model_year

In [20]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [21]:
df[df.origin == 'Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

Select the first 7 values

In [22]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

Get the underlying NumPy array. Let's call it X.

In [23]:
import numpy as np
X = np.array(df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [24]:
X.shape

(7, 2)

In [25]:
X.T.shape

(2, 7)

In [26]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [27]:
XTX.shape

(2, 2)

Invert XTX.

In [28]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [30]:
y.shape

(7,)

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [31]:
w= XTX_inv.dot(X.T).dot(y)
w.sum()

np.float64(0.5187709081074016)

In [32]:
w

array([0.01386421, 0.5049067 ])

In [33]:
w.shape

(2,)